//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CNCControl.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_COMMSDATA                   101
#define IDC_GRIDEDIT                    101
#define IDD_PATHPOSITION                103
#define IDR_PATHSPEED                   104
#define IDR_PATHANIMATE                 105
#define IDR_LOGVIEW                     105
#define IDR_MAINFRAME                   128
#define IDR_PARAMVIEW                   129
#define IDR_COMMSVIEW                   130
#define IDR_PATH                        131
#define IDR_GRAPHVIEW                   132
#define IDR_PATHNCI                     133
#define IDD_PORTSELECT                  134
#define IDR_MANUALCONTVIEW              134
#define IDD_DIAGNOSE                    135
#define IDR_MACHINESTATUSVIEW           135
#define IDR_PATHBAR                     136
#define IDR_PROBESAMPLEVIEW             136
#define IDB_BITMAP1                     152
#define IDD_MACHINEPATHSEGMENTS         154
#define IDR_MOTIONPLOTBAR               155
#define IDB_BITMAP2                     163
#define IDB_BITMAPBAR                   163
#define IDR_VIEWBAR                     164
#define IDD_MACHINEPROPERTIES           166
#define IDR_VIEWDIRBAR                  169
#define IDR_PLAYERBAR                   174
#define IDD_ANIMATIONSETTINGS           176
#define IDD_CONTROLSTATUS               185
#define IDD_SENDBYTES                   186
#define IDD_MANUALCONTROL               187
#define IDB_TOOLSIZE                    196
#define IDD_MACHINELIMITS               198
#define IDD_DIMENSIONS                  199
#define IDD_SETTOOL                     200
#define IDD_PROBESAMPLE                 202
#define IDD_MovementAcc                 203
#define IDD_GENERALOPTIONS              204
#define IDC_EDIT1                       1000
#define DLGN_VALUECHANGED               1000
#define IDC_EDIT2                       1001
#define IDC_EDIT_REG_ADDR               1002
#define IDC_EDIT_POSTRACKFRACTBITS      1002
#define IDC_RADIO1                      1003
#define IDC_RADIO2                      1004
#define IDC_RADIO3                      1005
#define IDC_RADIO4                      1006
#define IDC_EDIT_REG_VALUE              1007
#define IDC_BUTTON_BYTES_MEM            1022
#define IDC_BUTTON_BYTES_REG            1023
#define IDC_BUTTON_REQ_MEM              1024
#define IDC_BUTTON_SEND_MEM             1025
#define IDC_CHECK_INC_MEM_ADDR          1026
#define IDC_CHECK_INC_REG               1027
#define IDC_BUTTON_REQ_REG              1028
#define IDC_BUTTON_SEND_REG             1029
#define IDC_EDIT_REG_BANK               1033
#define IDC_EDIT_MEM_ADDR               1034
#define IDC_EDIT_MEM_VALUE              1035
#define IDC_CHECK_INC_REG_BANK          1036
#define IDC_EDIT3                       1037
#define IDC_EDIT4                       1038
#define IDC_EDIT5                       1039
#define IDC_EDIT6                       1040
#define IDC_EDIT7                       1041
#define IDC_EDIT8                       1042
#define IDC_EDIT9                       1043
#define IDC_EDIT_JERKY                  1043
#define IDC_EDIT10                      1044
#define IDC_EDIT_JERKZ                  1044
#define IDC_EDIT11                      1045
#define IDC_EDIT_ACCX                   1045
#define IDC_EDIT_ACCY                   1046
#define IDC_EDIT_ACCZ                   1047
#define ID_DEFAULT                      1048
#define IDC_ALLOWACCSTEP                1049
#define IDC_EDIT_SPEEDXY                1049
#define IDC_EDIT_SPEEDXYZ               1050
#define IDC_EDIT_FEEDRATE               1051
#define IDC_EDIT_BLNEGX                 1052
#define IDC_COMBO1                      1053
#define IDC_EDIT_BLNEGY                 1053
#define IDC_BUTTON1                     1054
#define IDC_EDIT_BLNEGZ                 1054
#define IDC_SCROLLBAR1                  1062
#define IDC_SPIN1                       1063
#define IDC_EDIT_VELX                   1064
#define IDC_EDIT_VELY                   1065
#define IDC_EDIT_VELZ                   1066
#define IDC_EDIT_JERKX                  1067
#define IDC_EDIT_RESTIME                1068
#define IDC_EDIT_RESACC                 1069
#define IDC_EDIT_RESVEL                 1070
#define IDC_EDIT_RESPOS                 1071
#define IDC_EDIT_CUSPANGLE              1072
#define IDC_EDIT_RATE                   1073
#define IDC_EDIT_BLPOSX                 1073
#define IDC_EDIT_BLPOSY                 1074
#define IDC_LIST1                       1075
#define IDC_EDIT_BLPOSZ                 1075
#define IDSEND                          1076
#define IDC_EDIT_MACHINE_POS            1077
#define IDC_EDIT_DPOSPERREV             1077
#define IDC_EDIT_MACHINE_VEL            1078
#define IDC_EDIT_COUNTSPERREV           1078
#define IDC_EDIT_MACHINE_POSTRACK       1079
#define IDC_EDIT_MACHINE_VELTRACK       1080
#define IDB_BUTTONLEFT                  1080
#define IDC_EDIT_MACHINE_POSERROR       1081
#define IDB_BUTTONRIGHT                 1081
#define IDC_EDIT_MACHINE_VELERROR       1082
#define IDB_BUTTONUP                    1082
#define IDC_EDIT_MACHINE_PATHTIME       1083
#define IDB_BUTTONDOWN                  1083
#define IDC_EDIT_MACHINE_PATHSTEP       1084
#define IDB_BUTTONSTOP                  1084
#define IDC_EDIT_MACHINE_POSERROR2      1085
#define IDC_BUTTON_INCZ                 1085
#define IDB_BUTTONUPLEFT                1085
#define IDC_BUTTON_DECZ                 1086
#define IDB_BUTTONUPRIGHT               1086
#define IDC_EDIT_MACHINE_POSERROR3      1086
#define IDC_EDIT_ACCSEG_TI              1087
#define IDC_BUTTON_STOPZ                1087
#define IDB_BUTTONDOWNLEFT              1087
#define IDC_EDIT_ACCSEG_PSI             1088
#define IDC_BUTTON_STOPXY               1088
#define IDB_BUTTONDOWNRIGHT             1088
#define IDC_EDIT_ACCSEG_TF              1089
#define IDC_BUTTON_INCY                 1089
#define IDC_EDIT_ACCSEG_PSF             1090
#define IDC_BUTTON_DECY                 1090
#define IDC_BUTTON_INCX                 1091
#define IDC_EDIT_MACHINE_POSERROR4      1091
#define IDC_BUTTON_DECX                 1092
#define IDC_EDIT_ACCSEG_ASI             1093
#define IDC_BUTTON_IXIY                 1093
#define IDC_EDIT_ACCSEG_ASF             1094
#define IDC_BUTTON_IXDY                 1094
#define IDC_EDIT_LIMIT_TI               1095
#define IDC_BUTTON_DXDY                 1095
#define IDC_EDIT_LIMIT_PSI              1096
#define IDC_BUTTON_DXIY                 1096
#define IDC_EDIT_LIMIT_TF               1097
#define IDC_EDIT_VELCHANGE              1097
#define IDC_EDIT_ACCRAMPVELCHANGE       1097
#define IDC_EDIT_LIMIT_PSF              1098
#define IDC_BUTTON_SETPARAM             1098
#define IDC_EDIT_PATH_TI                1099
#define IDC_BUTTON_ENABLE               1099
#define IDC_EDIT_PATH_PSI               1100
#define IDC_BUTTON_ENABLEX              1100
#define IDC_EDIT_PATH_TF                1101
#define IDC_BUTTON_ENABLEY              1101
#define IDC_EDIT_PATH_PSF               1102
#define IDC_BUTTON_ENABLEZ              1102
#define IDC_CHECK1                      1103
#define IDC_EDIT_ACCRAMPRATE            1103
#define IDC_CHECK_SETMINZ_TOS           1103
#define IDC_CHECK_FINISHCUT             1103
#define IDC_CHECK_LOGSAMPLES            1103
#define IDC_CHECK_SMOOTH_CURVES         1103
#define IDC_CHECK_SMOOTH_SEGS           1103
#define IDC_CHECK_USE_BL_CORR           1103
#define IDC_CHECK2                      1104
#define IDC_EDIT_ACCRAMPTIME            1104
#define IDC_CHECK_PROBEONSTOCK          1104
#define IDC_CHECK_SAMPLEPROBE           1104
#define IDC_CHECK_ADD_JOINING_TABS      1104
#define IDC_CHECK3                      1105
#define IDC_EDIT_ACCRAMPHOLDTIME        1105
#define IDC_CHECK_SENDSAMPLES           1105
#define IDC_EDIT_ACCSTEP                1106
#define IDC_CHECK_LOCKFIXEDVALUES       1106
#define IDC_EDIT_MACHINE_TI             1107
#define IDC_EDIT_ACCSTEPHOLDTIME        1107
#define IDC_EDIT_ACCSTEPVELCHANGE       1108
#define IDC_EDIT_MACHINE_TF             1109
#define IDC_RADIO_ACCTYPE1              1110
#define IDC_EDIT_MACHINE_ASI            1111
#define IDC_RADIO_ACCTYPE2              1111
#define IDC_EDIT_MACHINE_ASF            1112
#define IDC_COMBO_POSNEW                1113
#define IDC_BUTTON_MATCHTRACKER         1114
#define IDC_BUTTON_MOVETOPOS            1115
#define IDC_EDIT_POSNEWX                1117
#define IDC_EDIT_POSNEWY                1118
#define IDC_EDIT_POSNEWZ                1119
#define IDC_BUTTON_USEX                 1120
#define IDC_BUTTON_USEY                 1121
#define IDC_BUTTON_USEZ                 1122
#define IDC_EDIT_POSERRORX              1123
#define IDC_EDIT_POSERRORY              1124
#define IDC_EDIT_POSERRORZ              1125
#define IDC_EDIT_POSCURRX               1126
#define IDC_EDIT_POSCURRY               1127
#define IDC_EDIT_POSCURRZ               1128
#define IDC_EDIT_VELCURRX               1129
#define IDC_EDIT_VELCURRY               1130
#define IDC_EDIT_VELCURRZ               1131
#define IDC_COMBO_FEEDBACK              1132
#define IDC_COMBO_FEEDFOWARD            1133
#define IDC_EDIT_ERRORLAST              1134
#define IDC_EDIT_MINX                   1135
#define IDC_EDIT_MAXX                   1136
#define IDC_EDIT_MAXY                   1137
#define IDC_EDIT_MINY                   1138
#define IDC_EDIT_MINZ                   1139
#define IDC_EDIT_MAXZ                   1140
#define IDC_EDIT_ABSMINZ                1141
#define IDC_EDIT_POSSERVOX              1141
#define IDC_EDIT_ABSMAXZ                1142
#define IDC_EDIT_POSSERVOY              1142
#define IDC_EDIT_ABSMINX                1143
#define IDC_EDIT_POSSERVOZ              1143
#define IDC_EDIT_ABSMINY                1144
#define IDC_EDIT_ABSMAXY                1145
#define IDC_EDIT_ABSMAXX                1146
#define IDC_EDIT_CURRENTBASEZ           1147
#define IDC_EDIT_TOPOFSTOCKZ            1148
#define IDC_EDIT_STOCKTHICKNESS         1149
#define IDC_EDIT_TOSCLEARANCE           1150
#define IDC_EDIT_DIA1                   1151
#define IDC_EDIT_DIA2                   1152
#define IDC_STATIC_HEADING              1153
#define IDC_EDIT_FINISHRADIUS           1154
#define IDC_STATIC_VAL1                 1155
#define IDC_STATIC_VAL2                 1156
#define IDC_STATIC_FINISHRADIUS         1157
#define IDC_EDIT_FINISHDEPTH            1158
#define IDC_STATIC_FINISHDEPTH          1159
#define IDC_EDIT_DIA3                   1160
#define IDC_STATIC_VAL3                 1161
#define IDC_EDIT_DIA4                   1162
#define IDC_STATIC_VAL4                 1163
#define IDC_EDIT_MOUNT2ZAXISHEAD        1164
#define IDC_EDIT_CHUCK2MOUNT            1165
#define IDC_EDIT_TIP2CHUCK              1166
#define IDC_EDIT_BASETOP2TIP            1167
#define IDC_EDIT_VACUUMBOARD            1168
#define IDC_EDIT_BASEBOARD              1169
#define IDC_EDIT_AXISPOS                1170
#define IDC_EDIT_AXISADJUST             1171
#define IDC_EDIT_BASE2ZAXISHEAD         1172
#define IDC_EDIT_DIATOOL                1173
#define IDC_EDIT_PROBEREADING           1174
#define IDC_EDIT_PROBEADJUST            1175
#define IDC_EDIT_STOCK                  1176
#define IDC_EDIT_STOCKTOP2TIP           1177
#define IDC_BUTTON_CALPROBE             1178
#define IDC_BUTTON_RECALPROBE           1178
#define IDC_COMBO_LOGFILE               1188
#define IDC_EDIT_AXISHEAD2TIP           1190
#define IDC_EDIT_STOPPROBEEXT           1191
#define IDC_EDIT_POSPROBEX              1193
#define IDC_EDIT_POSPROBEY              1194
#define IDC_EDIT_POSPROBEZ              1195
#define IDC_EDIT_MAXPROBEEXT            1196
#define IDC_EDIT_MINDISTTOLOG           1197
#define IDC_EDIT_POSPROBETIPZ           1198
#define IDC_EDIT_ANGLECHANGEDETECT      1198
#define IDC_EDIT_PROBEREADINGZ          1201
#define IDC_CHECK_INCFILENAME           1202
#define IDC_BUTTON_PROBESAMPLER         1203
#define IDC_CHECK_USE_POS_CORR          1204
#define IDC_EDIT_HEIGHT                 1204
#define IDC_CHECK_USE_POS_CORRX         1205
#define IDC_EDIT_WIDTH                  1205
#define IDC_CHECK_USE_POS_CORRY         1206
#define IDC_EDIT_RAMP_LENGTH            1206
#define IDC_CHECK_USE_POS_CORRZ         1207
#define IDC_EDIT_LOW_PASS_MAX           1207
#define IDC_EDIT_SEGTOL                 1208
#define IDC_EDIT_SEGTOLDIRSET           1209
#define IDC_EDIT_SEGSTRAIGHTMIN         1210
#define IDC_EDIT_SEGANGCUSP             1211
#define ID_VIEW_PARAMETERS              32771
#define ID_MACHINE_OPENCOMMUNICATIONS   32772
#define ID_MACHINE_REQUESTALLPARAMETERS 32774
#define ID_MACHINE_SENDALLPARAMETERS    32775
#define ID_OPTIONS_PORTSELECT           32777
#define ID_OPTIONS_PORTCONFIG           32778
#define ID_MACHINE_CLOSECOMMUNICATIONS  32779
#define ID_MACHINE_OPENCLOSECOMMUNICATIONS 32780
#define ID_MACHINE                      32781
#define ID_MACHINE_LOOPBACK             32782
#define ID_MACHINE_SENDPARAMETER        32783
#define ID_MACHINE_REQUESTPARAMETER     32784
#define ID_VIEW_PARAMETERS_GENERAL      32785
#define ID_VIEW_PARAMETERS_AXIS         32786
#define ID_VIEW_PARAMETERS_ALL          32787
#define ID_PATH_SENDNEXTPATHDATA        32788
#define ID_PATH_SENDALLPATHDATA         32789
#define ID_PATH_REQUESTNEXTPATHDATA     32790
#define ID_PATH_REQUESTALLPATHDATA      32791
#define ID_MACHINE_DIAGNOSEBOX          32792
#define ID_PATH_FINDSPEEDS              32793
#define ID_BUTTON32807                  32807
#define ID_BUTTON32808                  32808
#define ID_BUTTON32809                  32809
#define ID_BUTTON32810                  32810
#define ID_BUTTON32811                  32811
#define ID_PREFERENCES_MACHINEPATHSEGMENTS 32814
#define ID_SHOWX                        32826
#define ID_SHOWY                        32827
#define ID_SHOWZ                        32828
#define ID_SHOWPOS                      32829
#define ID_SHOWVEL                      32830
#define ID_SHOWACC                      32831
#define ID_SHOWJERK                     32832
#define ID_SHOWREQUESTEDSEGS            32833
#define ID_SHOWACTUALSEGS               32834
#define ID_SHOWACTUALreqSEGS            32835
#define ID_VIEW_ZOOMOUT                 32836
#define ID_VIEW_ZOOMALL                 32837
#define ID_VIEW_ZOOM11                  32838
#define ID_SHOWENDNODES                 32840
#define ID_SHOWCTRLNODES                32841
#define ID_VIEW_ZOOMIN                  32843
#define ID_MACHINE_PROPERTIES           32844
#define ID_PATH_SEGMENTTRACKING         32847
#define ID_VIEW_STORE_LOC               32848
#define ID_VIEW_SET_LOC                 32849
#define ID_VIEW_PREV                    32850
#define ID_VIEW_NEXT                    32851
#define ID_VIEWDIR_X                    32852
#define ID_VIEWDIR_Y                    32853
#define ID_VIEWDIR_Z                    32854
#define ID_VIEWDIR_ISO                  32856
#define ID_PATH_ANIMATE                 32858
#define ID_PATH_ANIMATE_STOP            32861
#define ID_PATH_ANIMATE_START           32862
#define ID_PATH_ANIMATE_PAUSE           32864
#define ID_PATH_DOIT                    32871
#define ID_VIEW_SHOWREGION              32872
#define ID_OPTIONS_SCROLLBARS           32873
#define ID_VIEWDIR_FLIP                 32874
#define ID_PATHCOLORFEEDRATE            32877
#define ID_PATHCOLORCURVE               32878
#define ID_PATHSHOWORIG                 32879
#define ID_PATHSHOWFITTED               32880
#define ID_SHOWCTRLNODELINES            32881
#define ID_SHOWBEZIERS                  32882
#define ID_VIEW_ISOSCALE                32883
#define ID_ANIMATIONSETTINGS            32884
#define ID_MACHINE_SIMULATECONTROLLERRESPONSE 32890
#define ID_MACHINE_SIMULATERESPONSE     32891
#define ID_PATH_SENDSTART               32892
#define ID_PATH_SENDNEXT                32893
#define ID_PATH_SENDSTOP                32894
#define ID_MANUALCONTROL_CLOSED         32895
#define ID_PROBESAMPLE_CLOSED           32896
#define ID_MACHINE_VIEWCOMMSDATA        32897
#define ID_MACHINE_SHOWCOMMSDATA        32899
#define ID_MACHINE_LOGCOMMSDATA         32900
#define ID_MACHINE_SENDBYTES            32901
#define ID_PATH_SENDRESET               32902
#define ID_SENDPKTSTEP                  32903
#define ID_SENDPKT                      32904
#define ID_MACHINE_MANUALCONT           32906
#define ID_PATH_DOHOLEMATRIX            32907
#define ID_PATH_DOHOLEMATRIXCURVED      32908
#define ID_PATH_DOBOATSHED              32909
#define ID_PATH_DORECTANGLE             32910
#define ID_PATH_DOCIRCLE                32911
#define ID_PATH_DOBOATSHED1             32912
#define ID_PATH_DOBOATSHED2             32913
#define ID_PATH_DOBOATSHED3             32914
#define ID_PATH_DOHEART                 32915
#define ID_PATH_DOMINERET               32916
#define ID_PATH_DOMINARET               32917
#define ID_VIEW_LOG                     32918
#define ID_MACHINE_SHOWMACHINESTATUS    32919
#define ID_PATH_DOSTARHOLEMATRIX        32920
#define ID_PATH_HOLEMATRIXSERVOCALIBRATION 32921
#define ID_PATH_HOLEMATRIXSERVOCAL      32922
#define ID_PATH_HOLEMATRIXBASESCREWS    32923
#define ID_PATH_HOLEMATRIX              32924
#define ID_VIEW_TOOLBARS_PATHPOSITION   32925
#define ID_VIEW_PATHPOSITION_BAR        32926
#define ID_PATH_BASEVACUUMHOSEMATRIX    32929
#define ID_PATH_BASEVACUUMHOSESINGLEMATRIX 32930
#define ID_PATH_VACUUMBOARDTRENCHING    32931
#define ID_PATH_BASEVACUUMHOSEARRAY     32932
#define ID_PATH_BASEVACUUMHOSESINGLE    32933
#define ID_PATH_MANIFOLDVACUUMBOXARRAY  32934
#define ID_PATH_MANIFOLDVACUUMBOXSINGLE 32935
#define ID_MACHINE_SETTOOL              32936
#define ID_FILE_SAVESETTINGS            32937
#define ID_MACHINE_PROBESAMPLE          32939
#define ID_PATH_DEPTHCHECK              32940
#define ID_OPTIONS_SETTINGS             32941
#define ID_INDICATOR_POSITION           59143
#define IDW_FIRST_BAR                   0xe804
#define IDW_VIEW_BAR                    0xe804
#define IDW_MOTIONPLOT_BAR              0xe805
#define IDW_VIEWDIR_BAR                 0xe806
#define IDW_PLAYER_BAR                  0xe807
#define IDW_PATH_BAR                    0xe808
#define IDW_PATHPOSITION_BAR            0xe809
#define IDW_LAST_BAR                    0xe820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        205
#define _APS_NEXT_COMMAND_VALUE         32942
#define _APS_NEXT_CONTROL_VALUE         1205
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
